---
version: '3'

services:

  backend:
    image: viasite/site-audit-seo:latest
    container_name: ${NAMESPACE}-backend
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PORT: ${SERVER_PORT}
    ports:
    - 5301:${SERVER_PORT}
    # networks:
    # - internal
    # - web
    volumes:
    - ./data/reports:/app/data/reports

  frontend:
    image: viasite/site-audit-seo-viewer:latest
    container_name: ${NAMESPACE}-frontend
    build: data/front
    # env_file:
    # - data/popstas-server.env
    environment:
      HOST: 0.0.0.0 # for nuxt
      PORT: ${FRONT_PORT}
      SERVER_URL: ${SERVER_URL}
      FRONTEND_URL: ${FRONTEND_URL}
      JSON_URL: ${JSON_URL}

    ports:
    - 5302:${FRONT_PORT}
    # networks:
    # - web
    # volumes:
    # - ./data/reports:/app/static/reports

# networks:
#   internal:
#     driver: bridge
#   web:
#     external: true
