---
services:

  backend:
    image: viasite/site-audit-seo:latest-alpine
    container_name: ${NAMESPACE}-backend
    build:
      context: .
      dockerfile: Dockerfile
    expose:
    - 3000
    ports:
    - 3000:3000
    volumes:
    - ./outputs:/opt/output

  frontend:
    image: viasite/site-audit-seo-viewer:latest
    container_name: ${NAMESPACE}-frontend
    build:
      context: .
      dockerfile: Dockerfile.viewer
    expose:
    - 3001
    ports:
    - 3001:3001
    networks:
    - web

networks:
  web:
    external: true
