name: Trigger auto deployment for seoai-frontend

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/seoai-frontend-AutoDeployTrigger-075065dc-e1cc-4da1-b238-9767a0d6e2c1.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.SEOAIFRONTEND_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.SEOAIFRONTEND_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.SEOAIFRONTEND_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: auditseo.azurecr.io
          registryUsername: ${{ secrets.SEOAIFRONTEND_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.SEOAIFRONTEND_REGISTRY_PASSWORD }}
          containerAppName: seoai-frontend
          resourceGroup: BetaRG
          imageToBuild: auditseo.azurecr.io/seoai-frontend:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


